# the two root directories to take the data from and to store the data in
source: test/test_data/resources
# prot_cols: ["AASeq"]
# drug_cols: ["IUPAC"]

# only_prots: false
# seed: 42

# prots:
#   structs:
#     method: plddt # whole, template, bsite, plddt
#     bsite:
#       radius: 5
#     template:
#       radius: 2
#     plddt:
#       threshold: 70

#   features:
#     method: rinerator # distance or rinerator
#     distance:
#       threshold: 7
#     node_feats: label # label, onehot, or esm
#     edge_feats: none # label, onehot, or none

# drugs:
#   max_num_atoms: 150
#   node_feats: label
#   edge_feats: none

# split_data:
#   method: random # random, target, drug
#   train: 0.7
#   val: 0.2
#   # test is created as a remainder of train and val

# parse_dataset:
#   filtering: all # all, posneg
#   sampling: none # over, under, none
#   task: class # class, reg
#   # threshold values for class problem
#   threshold: 1.645
#   # Whether to apply logarithm with base of 10 to values (for reg, doesn't affect threshold  )
#   log: false
