runs: 1
name: lectinoracle_full
seed: 42
datamodule:
  # filename: /scratch/SCRATCH_SAS/roman/rindti/datasets/oracle_esm/results/prepare_all/elnwInranc_e7b53363.pkl
  filename: /scratch/SCRATCH_SAS/roman/rindti/datasets/oracle_esm/results/prepare_all/elnwInrbnc_8b492165.pkl
  exp_name: glylec_mbb
  batch_size: 64
  num_workers: 16
  dyn_sampler: False
transform:
  mode: none  # esm  # neighbors
  k: 3
  spots: 3
  graphs:
    main:
      weight: 4
    prot:
      weight: 1
trainer:
  gpus: 1
  max_epochs: 100
  profiler: null
  gradient_clip_val: 100
early_stop:
  patience: 125
  monitor: val_loss
  mode: min
checkpoints:
  monitor: val_Accuracy
  save_top_k: 3
  mode: max
model:
  module: class
  feat_method: concat
  drug:
    hidden_dim: 128
    method: sweetnet
    node:
      module: ginconv
      dropout: 0.1
      hidden_dim: 128
      num_layers: 3
    pool:
      module: gmt
      num_heads: 4
      hidden_dim: 128
      ratio: 0.25
  prot:
    hidden_dim: 128
    method: pretrained
    node:
      module: ginconv
      dropout: 0.1
      hidden_dim: 128
      num_layers: 3
    pool:
      module: gmt
      num_heads: 4
      hidden_dim: 128
      ratio: 0.25
    data:
      max_nodes: 1
      edge_type: none
      feat_type: onehot
      feat_dim: 1280
      edge_dim: 0
  mlp:
    dropout: 0.2
    hidden_dim: 512
  optimizer:
    module: adam
    single_lr: True
    lr: 0.0001
    prot_lr: 0.001
    drug_lr: 0.001
    weight_decay: 0.01
    momentum: 0.01
    lr_schedule:
      monitor: val_loss
      module: rlrop
      factor: 0.1
      patience: 20
