seed: 42
datamodule:
  filename: /scratch/SCRATCH_NVME/ilya/datasets/uniref50/resources/structures/
  batch_size: -1
  num_workers: 16
  shuffle: true
  batch_sampling: true
  max_num_nodes: 10000
  weighted_mask: false
  sigma: 0.75
  prob: 0.125
model:
  local_module: GAT
  global_module: Performer
  hidden_dim: 512
  num_layers: 6
  num_heads: 4
  alpha: 1.0
  dropout: 0.1
  attn_dropout: 0.1
  optimizer: Adam
  max_lr: 1.0e-4
  start_lr: 1.0e-5
  min_lr: 1.0e-7
  weighted_loss: false
