seed: 42
datamodule:
  filename: datasets/glass/results/prepare_all/pdlnpnclnr_2deeeb4b.pkl
  batch_size: 32
  num_workers: 16
model:
  prot_encoder:
    hidden_dim: 64
    processor: "graphgps"
    aggregator: "diffpool"
  drug_encoder:
    hidden_dim: 64
    processor: "graphgps"
    aggregator: "diffpool"
  optimizer: Adam
  max_lr: 0.0001
  start_lr: 0.00001
  min_lr: 1e-7
  warmup_epochs: 5
  max_epochs: 100
