from .bgrl import BGRLModel
from .classification import ClassificationModel
from .graphlog import GraphLogModel
from .infograph import InfoGraphModel
from .noisy_nodes_classification import NoisyNodesClassModel
from .noisy_nodes_regression import NoisyNodesRegModel
from .pfam import PfamModel
from .regression import RegressionModel
from .encoder import Encoder
