name: Test RINDTI

on:
  push:
    paths:
      - rindti/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/rindti

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: rindti
          use-mamba: true

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('workflow/envs/main.yaml') }}

      - if: ${{ steps.cache.outputs.cache-hit == false }}
        name: Update environment
        run: mamba env update -n rindti -f workflow/envs/main.yaml

      - name: Run tests
        shell: bash -l {0}
        run: pytest -m "not gpu and not snakemake" --cov=rindti --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
